# ============================================================
#  install.ps1  —  Node.js App Installer
#  Parameter diterima dari Inno Setup via command line
# ============================================================

param(
    [string]$InstallDir  = "C:\MyApp",
    [string]$AppPort     = "3000",
    [string]$NodePort    = "3000",
    [string]$MongoPort   = "27017",
    [string]$ZipUrl      = "https://example.com/app.zip",
    [string]$EnvExtra    = "",
    [switch]$UpdateMode  = $false
)

# ── Helpers ─────────────────────────────────────────────────
function Log($msg) { Write-Host "[INFO]  $msg" }
function Err($msg) { Write-Host "[ERROR] $msg" -ForegroundColor Red; exit 1 }
function Ok ($msg) { Write-Host "[OK]    $msg" -ForegroundColor Green }

function Is-Installed($cmd) {
    return $null -ne (Get-Command $cmd -ErrorAction SilentlyContinue)
}

function Download-File($url, $dest) {
    Log "Downloading $url ..."
    try {
        Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
        Ok "Downloaded -> $dest"
    } catch {
        Err "Gagal download: $_"
    }
}

# ── 1. Cek & Install Node.js ────────────────────────────────
function Install-NodeJS {
    if (Is-Installed "node") {
        $ver = node --version
        Ok "Node.js sudah terinstall ($ver) - skip."
        return
    }
    Log "Node.js belum ditemukan. Menginstall via winget..."
    try {
        winget install -e --id OpenJS.NodeJS.LTS --silent --accept-package-agreements --accept-source-agreements
        # Refresh PATH
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
                    [System.Environment]::GetEnvironmentVariable("Path", "User")
        Ok "Node.js berhasil diinstall."
    } catch {
        Err "Instalasi Node.js gagal. Pastikan winget tersedia atau install manual dari https://nodejs.org"
    }
}

# ── 2. Cek & Install MongoDB ────────────────────────────────
function Install-MongoDB {
    $svc = Get-Service -Name "MongoDB" -ErrorAction SilentlyContinue
    if ($svc) {
        Ok "MongoDB service sudah ada - skip."
        return
    }
    Log "MongoDB belum ditemukan. Menginstall via winget..."
    try {
        winget install -e --id MongoDB.Server --silent --accept-package-agreements --accept-source-agreements
        Start-Sleep -Seconds 5

        # Pastikan service berjalan
        Start-Service -Name "MongoDB" -ErrorAction SilentlyContinue
        Ok "MongoDB berhasil diinstall dan dijalankan."
    } catch {
        Err "Instalasi MongoDB gagal: $_"
    }
}

# ── 3. Download & Extract ZIP ───────────────────────────────
function Download-App {
    $zipPath = "$env:TEMP\app_package.zip"
    Download-File $ZipUrl $zipPath

    if (-not (Test-Path $InstallDir)) {
        New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    }

    Log "Mengextract ke $InstallDir ..."
    try {
        Expand-Archive -Path $zipPath -DestinationPath $InstallDir -Force
        Ok "Extract selesai."
    } catch {
        Err "Gagal extract ZIP: $_"
    }
    Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
}

# ── 4. Buat file .env ───────────────────────────────────────
function Create-Env {
    $envFile = "$InstallDir\.env"

    $content = @"
# Auto-generated by Installer
PORT=$AppPort
MONGO_URI=mongodb://localhost:$MongoPort/myapp
NODE_ENV=production
"@

    if ($EnvExtra -ne "") {
        $CleanEnvExtra = $EnvExtra -replace '\[NL\]', "`n"
        $content += "`n# Extra config`n$CleanEnvExtra"
    }

    Set-Content -Path $envFile -Value $content -Encoding UTF8
    Ok ".env dibuat di $envFile"
}

# ── 5. npm install ──────────────────────────────────────────
function Run-NpmInstall {
    Log "Menjalankan npm install di $InstallDir ..."
    Push-Location $InstallDir
    try {
        & npm install --omit=dev 2>&1 | Tee-Object -FilePath "$InstallDir\npm-install.log"
        Ok "npm install selesai."
    } catch {
        Err "npm install gagal: $_"
    } finally {
        Pop-Location
    }
}

# ── 6. Install & Start PM2 ──────────────────────────────────
function Setup-PM2 {
    if (-not (Is-Installed "pm2")) {
        Log "Menginstall PM2 secara global..."
        & npm install -g pm2 2>&1 | Out-Null
        Ok "PM2 berhasil diinstall."
    } else {
        Ok "PM2 sudah terinstall - skip."
    }

    # Deteksi entry point
    $entry = ""
    foreach ($candidate in @("app.js", "index.js", "server.js", "main.js")) {
        if (Test-Path "$InstallDir\$candidate") { $entry = $candidate; break }
    }
    if ($entry -eq "") { Err "Entry point (app.js/index.js/server.js) tidak ditemukan di $InstallDir" }

    Log "Memulai aplikasi dengan PM2 (entry: $entry)..."
    Push-Location $InstallDir
    & pm2 start $entry --name "myapp" -- --port $AppPort 2>&1 | Out-Null
    & pm2 save 2>&1 | Out-Null

    # Daftarkan PM2 startup agar otomatis jalan saat Windows boot
    & pm2 startup 2>&1 | Out-Null
    Pop-Location
    Ok "Aplikasi berjalan via PM2."
}

# ── UPDATE MODE ─────────────────────────────────────────────
function Run-Update {
    Log "=== MODE UPDATE ==="
    Download-App
    Run-NpmInstall

    Log "Merestart aplikasi PM2..."
    & pm2 restart myapp 2>&1 | Out-Null
    Ok "Update selesai. Aplikasi direstart."
}

# ── MAIN ────────────────────────────────────────────────────
Log "============================================"
Log " Node.js App Installer"
Log " Install Dir : $InstallDir"
Log " App Port    : $AppPort"
Log " Mongo Port  : $MongoPort"
Log "============================================"

if ($UpdateMode) {
    Run-Update
} else {
    Install-NodeJS
    Install-MongoDB
    Download-App
    Create-Env
    Run-NpmInstall
    Setup-PM2
}

Log ""
Ok "Semua proses selesai!"
Log "Akses aplikasi di: http://localhost:$AppPort"